name: Bug Report
description: Bug Report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
        Please check below before submitting new issue:
        1. Please check if there is an issue with the same content.
        2. Please update the app latest version.
        3. Please upload the log if the issue is related to log reading.
          **Log location:** `%LOCALAPPDATA%Low\Mediatonic\FallGuys_client`
          Saved to `Player.log` or `Player-prev.log`(previous session) of the directory.
          Also, the time or line number helps us!
        4. Please upload the image if the error has showed.
        5. Please upload the `data.db` if the issue is related to database or saving datas.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please Upload files to this section.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you playing? Please answer if the issue is related to Launch FallGuys or log reading.
      options:
        - Steam
        - Epic Games
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for your report! Check your title and texts. Push "Submit new issue" to finish!
